<a href="https://colab.research.google.com/github/sk-shahsi/ML_Model/blob/master/OLS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
import pandas as pd
import numpy as np

In [43]:
df = pd.read_csv('/content/Salary_dataset.csv')

In [44]:
df

    Unnamed: 0  YearsExperience    Salary
0            0              1.2   39344.0
1            1              1.4   46206.0
2            2              1.6   37732.0
3            3              2.1   43526.0
4            4              2.3   39892.0
5            5              3.0   56643.0
6            6              3.1   60151.0
7            7              3.3   54446.0
8            8              3.3   64446.0
9            9              3.8   57190.0
10          10              4.0   63219.0
11          11              4.1   55795.0
12          12              4.1   56958.0
13          13              4.2   57082.0
14          14              4.6   61112.0
15          15              5.0   67939.0
16          16              5.2   66030.0
17          17              5.4   83089.0
18          18              6.0   81364.0
19          19              6.1   93941.0
20          20              6.9   91739.0
21          21              7.2   98274.0
22          22              8.0  101303.0
23          23              8.3  113813.0
24          24              8.8  109432.0
25          25              9.1  105583.0
26          26              9.6  116970.0
27          27              9.7  112636.0
28          28             10.4  122392.0
29          29             10.6  121873.0

In [45]:
df.columns

Index(['Unnamed: 0', 'YearsExperience', 'Salary'], dtype='object')

In [46]:
x = df['YearsExperience']
y= df['Salary']

In [47]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [48]:
x_train = pd.DataFrame(x_train)
x_test = pd.DataFrame(x_test)
y_train = pd.DataFrame(y_train)
y_test = pd.DataFrame(y_test)

In [49]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [50]:
y_pred = model.predict(x_test)

In [51]:
from sklearn.metrics import *

In [52]:
r2_score(y_test,y_pred)

0.9024461774180497

In [53]:
mean_squared_error(y_test,y_pred)

49830096.855908394

In [54]:
df

    Unnamed: 0  YearsExperience    Salary
0            0              1.2   39344.0
1            1              1.4   46206.0
2            2              1.6   37732.0
3            3              2.1   43526.0
4            4              2.3   39892.0
5            5              3.0   56643.0
6            6              3.1   60151.0
7            7              3.3   54446.0
8            8              3.3   64446.0
9            9              3.8   57190.0
10          10              4.0   63219.0
11          11              4.1   55795.0
12          12              4.1   56958.0
13          13              4.2   57082.0
14          14              4.6   61112.0
15          15              5.0   67939.0
16          16              5.2   66030.0
17          17              5.4   83089.0
18          18              6.0   81364.0
19          19              6.1   93941.0
20          20              6.9   91739.0
21          21              7.2   98274.0
22          22              8.0  101303.0
23          23              8.3  113813.0
24          24              8.8  109432.0
25          25              9.1  105583.0
26          26              9.6  116970.0
27          27              9.7  112636.0
28          28             10.4  122392.0
29          29             10.6  121873.0

In [55]:
df.drop(columns="Unnamed: 0",inplace = True)

In [56]:
df

    YearsExperience    Salary
0               1.2   39344.0
1               1.4   46206.0
2               1.6   37732.0
3               2.1   43526.0
4               2.3   39892.0
5               3.0   56643.0
6               3.1   60151.0
7               3.3   54446.0
8               3.3   64446.0
9               3.8   57190.0
10              4.0   63219.0
11              4.1   55795.0
12              4.1   56958.0
13              4.2   57082.0
14              4.6   61112.0
15              5.0   67939.0
16              5.2   66030.0
17              5.4   83089.0
18              6.0   81364.0
19              6.1   93941.0
20              6.9   91739.0
21              7.2   98274.0
22              8.0  101303.0
23              8.3  113813.0
24              8.8  109432.0
25              9.1  105583.0
26              9.6  116970.0
27              9.7  112636.0
28             10.4  122392.0
29             10.6  121873.0

In [57]:
#OLS

In [58]:
x1=df[["YearsExperience"]].values
y1=df["Salary"].values

In [59]:
x1_train,x1_test,y1_test,y1_train=train_test_split(x1,y1,test_size=0.2,random_state=42)

In [60]:
import numpy as np

In [61]:
x_train_ols = np.hstack((np.ones((x_train.shape[0],1)),x_train))
x_test_ols = np.hstack((np.ones((x_test.shape[0],1)),x_test))

In [62]:
x_train_ols

array([[ 1. , 10.4],
       [ 1. ,  8.8],
       [ 1. ,  4.1],
       [ 1. ,  1.2],
       [ 1. ,  2.3],
       [ 1. ,  5.2],
       [ 1. ,  3. ],
       [ 1. ,  4.2],
       [ 1. ,  4.1],
       [ 1. ,  8. ],
       [ 1. ,  1.4],
       [ 1. ,  1.6],
       [ 1. ,  9.1],
       [ 1. ,  2.1],
       [ 1. ,  7.2],
       [ 1. ,  9.6],
       [ 1. ,  6. ],
       [ 1. , 10.6],
       [ 1. ,  6.9],
       [ 1. ,  3.3],
       [ 1. ,  4. ],
       [ 1. ,  4.6],
       [ 1. ,  6.1],
       [ 1. ,  3.1]])

In [63]:
x_transpose_ols = x_train_ols.T

In [64]:
x_transpose_ols

array([[ 1. ,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ,
         1. ,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ,
         1. ,  1. ],
       [10.4,  8.8,  4.1,  1.2,  2.3,  5.2,  3. ,  4.2,  4.1,  8. ,  1.4,
         1.6,  9.1,  2.1,  7.2,  9.6,  6. , 10.6,  6.9,  3.3,  4. ,  4.6,
         6.1,  3.1]])

In [65]:
beta = np.linalg.inv(x_transpose_ols @ x_train_ols) @ x_transpose_ols @ y_train

In [66]:
y_pred_ols = x_test_ols @ beta

In [67]:
y_pred_ols

          Salary
0  115791.210113
1   71499.278095
2  102597.868661
3   75268.804224
4   55478.792045
5   60190.699707

In [68]:
y1_test

array([122392., 109432.,  56958.,  39344.,  39892.,  66030.,  56643.,
        57082.,  55795., 101303.,  46206.,  37732., 105583.,  43526.,
        98274., 116970.,  81364., 121873.,  91739.,  54446.,  63219.,
        61112.,  93941.,  60151.])

In [69]:
r2_score(y1_test,y_pred_ols)

ValueError: Found input variables with inconsistent numbers of samples: [24, 6]

In [70]:
mean_squared_error(y1_test,y_pred_ols)

ValueError: Found input variables with inconsistent numbers of samples: [24, 6]