<a href="https://colab.research.google.com/github/sk-shahsi/ML_Model/blob/master/PCA_Practical_16_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [53]:
import pandas as pd
import numpy as np
import seaborn as sns

In [54]:
df=pd.read_csv("/content/nba_final.csv")

In [55]:
df

,Rk,Player.x,Player_ID,Pos1,Pos2,Age,Tm,G,GS,MP,...,Conference,Role,Fvot,FRank,Pvot,PRank,Mvot,MRank,Score,Play
0,170,A.J. Hammons,hammoaj01,C,NaN,24,DAL,22,0,7.4,...,West,Front,786,123,NaN,NaN,NaN,NaN,83.5,No
1,58,Aaron Brooks,brookaa01,PG,NaN,32,IND,65,0,13.8,...,Est,Back,2474,64,NaN,NaN,NaN,NaN,48.2,No
2,157,Aaron Gordon,gordoaa01,SF,NaN,21,ORL,80,72,28.7,...,Est,Front,22774,29,NaN,NaN,NaN,NaN,40.0,No
3,352,Adreian Payne,paynead01,PF,NaN,25,MIN,18,0,7.5,...,West,Front,861,120,1.0,52.0,NaN,NaN,75.5,No
4,10,Al-Farouq Aminu,aminual01,PF,NaN,26,POR,61,25,29.1,...,West,Front,4971,69,7.0,23.0,NaN,NaN,42.8,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1403,109,Zach Collins,colliza01,C,NaN,21,POR,77,0,17.6,...,West,Front,16287,74,1.0,52.0,0.0,8.0,86.8,No
1404,294,Zach LaVine,lavinza01,SG,NaN,23,CHI,63,62,34.5,...,Est,Back,519746,7,17.0,8.0,0.0,8.0,36.5,No
1405,308,Zach Lofton,loftoza01,SG,NaN,26,DET,1,0,4.0,...,Est,Back,136,114,0.0,61.0,0.0,8.0,132.2,No
1406,393,Zaza Pachulia,pachuza01,C,NaN,34,DET,68,3,12.9,...,Est,Front,21525,50,2.0,41.0,0.0,7.0,69.8,No
1407,457,Zhaire Smith,smithzh01,SG,NaN,19,PHI,6,2,18.5,...,Est,Back,3985,91,0.0,61.0,0.0,8.0,120.8,No

In [56]:
#Tell us number of row and columns prsent in data
df.shape

(1408, 45)

In [57]:
#print the datatype of values prsent in each column
df.dtypes

Rk              int64
Player.x       object
Player_ID      object
Pos1           object
Pos2           object
Age             int64
Tm             object
G               int64
GS              int64
MP            float64
FG            float64
FGA           float64
FG.           float64
X3P           float64
X3PA          float64
X3P.          float64
X2P           float64
X2PA          float64
X2P.          float64
eFG.          float64
FT            float64
FTA           float64
FT.           float64
ORB           float64
DRB           float64
TRB           float64
AST           float64
STL           float64
BLK           float64
TOV           float64
PF            float64
PTS           float64
Salary        float64
mean_views    float64
Season         object
Conference     object
Role           object
Fvot            int64
FRank           int64
Pvot          float64
PRank         float64
Mvot          float64
MRank         float64
Score         float64
Play           object
dtype: object

In [58]:
df.isnull().sum()

Rk               0
Player.x         0
Player_ID        0
Pos1             0
Pos2          1396
Age              0
Tm               0
G                0
GS               0
MP               0
FG               0
FGA              0
FG.              4
X3P              0
X3PA             0
X3P.            99
X2P              0
X2PA             0
X2P.            15
eFG.             4
FT               0
FTA              0
FT.             47
ORB              0
DRB              0
TRB              0
AST              0
STL              0
BLK              0
TOV              0
PF               0
PTS              0
Salary          62
mean_views     138
Season           0
Conference       0
Role             0
Fvot             0
FRank            0
Pvot           159
PRank          159
Mvot           404
MRank          404
Score            0
Play             0
dtype: int64

In [59]:
df['Age'].astype(object)
# alwys remove the missing value before changing the data types of any columns

0       24
1       32
2       21
3       25
4       26
        ..
1403    21
1404    23
1405    26
1406    34
1407    19
Name: Age, Length: 1408, dtype: object

In [60]:
df.isnull().sum(axis=0)

Rk               0
Player.x         0
Player_ID        0
Pos1             0
Pos2          1396
Age              0
Tm               0
G                0
GS               0
MP               0
FG               0
FGA              0
FG.              4
X3P              0
X3PA             0
X3P.            99
X2P              0
X2PA             0
X2P.            15
eFG.             4
FT               0
FTA              0
FT.             47
ORB              0
DRB              0
TRB              0
AST              0
STL              0
BLK              0
TOV              0
PF               0
PTS              0
Salary          62
mean_views     138
Season           0
Conference       0
Role             0
Fvot             0
FRank            0
Pvot           159
PRank          159
Mvot           404
MRank          404
Score            0
Play             0
dtype: int64

In [61]:
df.isnull().sum(axis=1)

0       6
1       5
2       5
3       3
4       3
       ..
1403    1
1404    1
1405    4
1406    1
1407    1
Length: 1408, dtype: int64

In [62]:
df.drop(columns='Pos2',inplace=True)

In [63]:
df=df.fillna(0)

In [64]:
#check for duplicates
df.duplicated().sum()

np.int64(0)

In [65]:
#deleting useless colums
df.drop(columns=['Player.x',"Player_ID"],inplace=True)

**Encoding the catogorical columns using LableEncoder**

In [66]:
obj_col = df.select_dtypes(object).columns

In [67]:
print(obj_col)

Index(['Pos1', 'Tm', 'Season', 'Conference', 'Role', 'Play'], dtype='object')

In [68]:
from sklearn.preprocessing import LabelEncoder,StandardScaler

In [69]:
le=LabelEncoder()
for col in obj_col:
  df[col] =le.fit_transform(df[col])

In [70]:
df['Play'].value_counts()
#check for data imblance

Play
0    1335
1      73
Name: count, dtype: int64

In [71]:
print(1335/1408)
print(73/1408)

0.9481534090909091
0.05184659090909091

***3. Machine Learning Process***

In [72]:
x=df.drop(columns='Play')
y=df['Play']

In [73]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_tes=train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)

In [74]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

***Apply Logistic Regression***

In [75]:
from sklearn.linear_model import LogisticRegression

In [76]:
log_reg = LogisticRegression()
log_reg.fit(x_train_scaled,y_train)

LogisticRegression()

In [77]:
y_pred = log_reg.predict(x_test_scaled)

In [78]:
from sklearn.metrics import accuracy_score

In [79]:
accuracy_score(y_tes,y_pred)

0.9787234042553191

***Now let's apply LDA on this dataset***

In [80]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [81]:
lda = LinearDiscriminantAnalysis()

In [82]:
x_train_lda = lda.fit_transform(x_train_scaled,y_train)
x_test_lda = lda.transform(x_test_scaled)

**min(n_classes-1,n_features)**

In [83]:
x_train_lda.shape

(1126, 1)

In [84]:
log_reg_3 = LogisticRegression()
log_reg_3.fit(x_train_lda,y_train)

LogisticRegression()

In [85]:
y_pred_3 = log_reg_3.predict(x_test_lda)

In [86]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,roc_auc_score

In [87]:
roc_auc_score(y_tes,y_pred_3)

np.float64(0.7925093632958802)

In [88]:
matrix = np.random.randint(10,51,size=(10,10))

In [89]:
np.linalg.det(matrix)

np.float64(-250462198718035.25)