<a href="https://colab.research.google.com/github/sk-shahsi/ML_Model/blob/master/SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Support vector  machine(SVM) is a machine learning algorithim used for booth classification and regression

In [30]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [31]:
df = pd.read_csv('/content/drug.csv')

In [32]:
df

     Age Sex      BP Cholesterol  Na_to_K   Drug
0     23   F    HIGH        HIGH   25.355  DrugY
1     47   M     LOW        HIGH   13.093  drugC
2     47   M     LOW        HIGH   10.114  drugC
3     28   F  NORMAL        HIGH    7.798  drugX
4     61   F     LOW        HIGH   18.043  DrugY
..   ...  ..     ...         ...      ...    ...
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

[200 rows x 6 columns]

In [33]:
df.isnull().sum()

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64

In [34]:
df.duplicated().sum()

np.int64(0)

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Age          200 non-null    int64
 1   Sex          200 non-null    object
 2   BP           200 non-null    object
 3   Cholesterol  200 non-null    object
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB

In [36]:
df.describe()

              Age     Na_to_K
count  200.000000  200.000000
mean    44.315000   16.084485
std     16.544315    7.223956
min     15.000000    6.269000
25%     31.000000   10.445500
50%     45.000000   13.936500
75%     58.000000   19.380000
max     74.000000   38.247000

In [37]:
df.describe(include='O')

        Sex    BP Cholesterol   Drug
count   200   200         200    200
unique    2     3           2      5
top       M  HIGH        HIGH  DrugY
freq    104    77         103     91

In [38]:
df['BP'].value_counts()

BP
HIGH      77
LOW       64
NORMAL    59
Name: count, dtype: int64

In [39]:
df.columns

Index(['Age', 'Sex', 'BP', 'Cholesterol', 'Na_to_K', 'Drug'], dtype='object')

In [40]:
df["Cholesterol"].value_counts()

Cholesterol
HIGH      103
NORMAL     97
Name: count, dtype: int64

In [41]:
df['Drug'].value_counts()

Drug
DrugY    91
drugX    54
drugA    23
drugC    16
drugB    16
Name: count, dtype: int64

In [42]:
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder

In [21]:
for i in df.columns:
  le=LabelEncoder()
  if df[i].dtype =="object":
    df[i] = le.fit_transform(df[i])

In [43]:
df.head()

   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [44]:
l1 = ['Sex',"Drug"]
l2 = ["BP","Cholesterol"]

In [45]:
for i in l1:
  df[i]=le.fit_transform(df[i])

In [46]:
oe = OrdinalEncoder(categories=[["LOW","NORMAL","HIGH"],["NORMAL","HIGH"]])

In [47]:
df[l2] = oe.fit_transform(df[l2])

In [48]:
df.head()

   Age  Sex   BP  Cholesterol  Na_to_K  Drug
0   23    0  2.0          1.0   25.355     0
1   47    1  0.0          1.0   13.093     3
2   47    1  0.0          1.0   10.114     3
3   28    0  1.0          1.0    7.798     4
4   61    0  0.0          1.0   18.043     0

In [49]:
from sklearn.model_selection import train_test_split

In [52]:
x_train,x_test,y_train,y_test = train_test_split(df.drop('Drug',axis=1),df['Drug'],test_size=0.2,random_state=42)

In [ ]:
sns.scatterplot(data=df,x="BP",y="Sex",)

In [53]:
from sklearn.svm import SVC

In [54]:
model = SVC(kernel="rbf")

In [55]:
model.fit(x_train,y_train)

SVC()

In [56]:
result = pd.DataFrame()
result["Actual"] = y_test
ypred = model.predict(x_test)
result["Predicted"] = ypred

In [58]:
result

     Actual  Predicted
95        4          4
15        0          0
30        4          4
158       3          4
128       0          0
115       0          0
69        0          0
170       4          4
174       1          4
45        4          4
66        1          4
182       4          4
165       0          0
78        1          4
186       2          4
177       0          0
56        2          4
152       4          4
82        3          4
68        0          0
124       2          4
16        4          4
148       4          4
93        0          0
65        0          0
60        0          0
84        3          4
67        4          4
125       0          0
132       4          4
9         0          0
18        3          4
55        3          0
75        0          0
150       1          4
104       0          0
135       4          0
137       1          4
164       0          0
76        1          4

In [59]:
from sklearn.metrics import*

In [60]:
accuracy_score(y_test,ypred)

0.625